# Site settings
title: Emil Högstedt
email: emil.hogstedt@hotmail.com
url: https://github.com/EmilHogstedt/EmilHogstedt.github.io
description: "The portfolio of Emil Högstedt. I am a M.Sc graduate with a degree in Software- and Game Development. My passion is creating games and experiences for other people to enjoy. I have work experience in all parts of indie game development, and have thorough knowledge of the backend that makes games run."
keywords: "your keywords, separated by commas"
skills: "Gameplay-, UI-, Engine Programmer"
meta_author: Emil Högstedt

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: M.Sc Emil Högstedt
  location: Located
  social: My Socials
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/emil.hogstedt
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/EmilHogstedt/
  - title: linkedin
    url: https://www.linkedin.com/in/emil-hogstedt/

# Postal address (add as many lines as necessary)
address:
  - line: Annebovägen 4C
  - line: 371 41, Karlskrona, Sweden

# Credits content
credits: "Content added by Emil Högstedt, Template from https://github.com/jeromelachaud/freelancer-theme"

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
